export const MULTIPLAYER_CREATE_GAME = 'MULTIPLAYER_CREATE_GAME';
export const MULTIPLAYER_FETCH_GAMES_BY_CLIENT =
  'MULTIPLAYER_FETCH_GAMES_BY_CLIENT';
export const MULTIPLAYER_FETCH_GAME = 'MULTIPLAYER_FETCH_GAME';
export const MULTIPLAYER_JOIN_GAME = 'MULTIPLAYER_JOIN_GAME';
export const MULTIPLAYER_SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const MULTIPLAYER_GENERATE_SUBREDDIT = 'MULTIPLAYER_GENERATE_SUBREDDIT';
export const MULTIPLAYER_SUBMIT_GUESS = 'MULTIPLAYER_SUBMIT_GUESS';
export const MULTIPLAYER_COMPLETE_ROUND = 'MULTIPLAYER_COMPLETE_ROUND';
export const MULTIPLAYER_ADD_SCORES = 'MULTIPLAYER_ADD_SCORES';
export const MULTIPLAYER_CLEAR_CURRENT_GAME = 'MULTIPLAYER_CLEAR_CURRENT_GAME';
export const MULTIPLAYER_CREATE_MESSAGE = 'MULTIPLAYER_CREATE_MESSAGE';
export const MULTIPLAYER_FETCH_MESSAGES = 'MULTIPLAYER_FETCH_MESSAGES';
export const MULTIPLAYER_NEW_MESSAGE_RECEIVED =
  'MULTIPLAYER_NEW_MESSAGE_RECEIVED';
export const MULTIPLAYER_DISMISS_NOTIFICATION =
  'MULTIPLAYER_DISMISS_NOTIFICATION';
export const MULTIPLAYER_SET_CLIENT_ID = 'MULTIPLAYER_SET_CLIENT_ID';
export const SERVE_ERROR = 'SERVE_ERROR';
