export const CREATE_MULTIPLAYER_GAME = 'CREATE_MULTIPLAYER_GAME';
export const FETCH_MULTIPLAYER_GAMES = 'FETCH_MULTIPLAYER_GAMES';
export const FETCH_MULTIPLAYER_GAME = 'FETCH_MULTIPLAYER_GAME';
export const JOIN_MULTIPLAYER_GAME = 'JOIN_MULTIPLAYER_GAME';
export const MULTIPLAYER_GENERATE_SUBREDDIT = 'MULTIPLAYER_GENERATE_SUBREDDIT';
export const MULTIPLAYER_SUBMIT_GUESS = 'MULTIPLAYER_SUBMIT_GUESS';
export const MULTIPLAYER_COMPLETE_ROUND = 'MULTIPLAYER_COMPLETE_ROUND';
export const MULTIPLAYER_ADD_SCORES = 'MULTIPLAYER_ADD_SCORES';
export const MULTIPLAYER_CLEAR_CURRENT_GAME = 'MULTIPLAYER_CLEAR_CURRENT_GAME';
export const MULTIPLAYER_CREATE_MESSAGE = 'MULTIPLAYER_CREATE_MESSAGE';
export const MULTIPLAYER_FETCH_MESSAGES = 'MULTIPLAYER_FETCH_MESSAGES';
export const MULTIPLAYER_NEW_MESSAGE_RECEIVED =
  'MULTIPLAYER_NEW_MESSAGE_RECEIVED';
export const MULTIPLAYER_DISMISS_NOTIFICATION =
  'MULTIPLAYER_DISMISS_NOTIFICATION';
export const SERVE_ERROR = 'SERVE_ERROR';
